### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by evenstensberg** [polarofficial/accesslink-example-python#15]
Hi, I'm having difficulties authorizing using the sample app. Here's a screenshot of what happens when I navigate to the localhost site. Any ideas?

<img width="1440" alt="Screen Shot 2020-06-19 at 19 26 14" src="https://user-images.githubusercontent.com/16735925/85163224-d2b77900-b262-11ea-8aab-1c34a4644855.png">

**Comment by palporkolab** [comment]
I have the same issue, also it is not working from the cmd line.
![Annotation 2020-06-23 195318](https://user-images.githubusercontent.com/67348648/85478972-3e635400-b58b-11ea-8433-f0c37ddeb9e5.jpg)

**Comment by patrickkusebauch** [comment]
I had the same issue. I contacted support and in the end, the problem was with the redirect URL set for the application in polar administration.

The polar app expects you to give a fully qualified name even if the field is described that it only requires a domain. What do I mean?

This works:
```
http://localhost:8080/saas.personal.profile/connect-account-response
```

NONE of those will work:
```
localhost
localhost:8080
localhost:8080/saas.personal.profile/connect-account-response
```

Yes they expect you to give you the full path, INCLUDING the scheme and the port as well.

![Screenshot from 2020-07-01 19-40-28](https://user-images.githubusercontent.com/1620948/86274999-dcca6780-bbd2-11ea-8de7-68c8e169ba08.png)

**Comment by palporkolab** [comment]
Thanks for the reply. Could you be please a bit more specific with regards to the given authorization.py code?
What exactly should I change in that to give the full redirect url as you suggested?

**Comment by patrickkusebauch** [comment]
@palporkolab In both the python code AND on the polar accesslink website you have to provide the fully qualified URI, Including, but not limited to the SCHEME and the PORT:

Basically the value for the redirect URI has to be exactly the same for both places.

**Comment by allanw** [comment]
I set the callback to http://localhost:5000/oauth2_callback as per the instructions but I'm getting the following error when I try to authorise:

`requests.exceptions.HTTPError: 401 Unauthorized: {"error":"invalid_client"}`

EDIT: Just saw the open pull request - that fixed the issue.

**Comment by irunner-kang** [comment]
I got the error message , "400 invalid_grant", no matter I reset the client key and secret(after changing I used the new one to generate the auth url off course)... is there any simular issue reported?

**Comment by twarmuz** [comment]
Hello trying first steps and failing already, I think I have the same issue as @evenstensberg initially but couldn't find good solution:

CALLBACK_PORT = 5000
CALLBACK_ENDPOINT = "/oauth2_callback"
REDIRECT_URL = f"http://localhost:{CALLBACK_PORT}{CALLBACK_ENDPOINT}"

when running authorization.py

I get following
![image](https://user-images.githubusercontent.com/39680191/111776760-b2305400-88b2-11eb-8eda-06f058e94034.png)

trying to authenticate the user in: 'https://flow.polar.com/oauth2/authorization?response_type=code&client_id=CLIENT_ID' showed me the page in the browser where I could authenticate to Polar Flow... but then it probably had problems to redirect... regardless I have the right callback configured

![image](https://user-images.githubusercontent.com/39680191/111777071-13f0be00-88b3-11eb-932e-8a6c3857201b.png)

What possibly goes wrong? something wrong with my flask? how to troubleshoot?
![image](https://user-images.githubusercontent.com/39680191/111777140-2cf96f00-88b3-11eb-8a84-9acc9794228d.png)

**Comment by AlbertFlorinus** [comment]
I sent a pull request, what solved it for me was changing "yaml.load(f)" to "yaml.safe_load(f)" utils.py

**Comment by AlbertFlorinus** [comment]
> Hello trying first steps and failing already, I think I have the same issue as @evenstensberg initially but couldn't find good solution:
> 
> CALLBACK_PORT = 5000 CALLBACK_ENDPOINT = "/oauth2_callback" REDIRECT_URL = f"[http://localhost:{CALLBACK_PORT}{CALLBACK_ENDPOINT}](http://localhost:%7BCALLBACK_PORT%7D%7BCALLBACK_ENDPOINT%7D)"
> 
> when running authorization.py
> 
> I get following ![image](https://user-images.githubusercontent.com/39680191/111776760-b2305400-88b2-11eb-8eda-06f058e94034.png)
> 
> trying to authenticate the user in: 'https://flow.polar.com/oauth2/authorization?response_type=code&client_id=CLIENT_ID' showed me the page in the browser where I could authenticate to Polar Flow... but then it probably had problems to redirect... regardless I have the right callback configured
> 
> ![image](https://user-images.githubusercontent.com/39680191/111777071-13f0be00-88b3-11eb-932e-8a6c3857201b.png)
> 
> What possibly goes wrong? something wrong with my flask? how to troubleshoot? ![image](https://user-images.githubusercontent.com/39680191/111777140-2cf96f00-88b3-11eb-8a84-9acc9794228d.png)

I sent a pull request, what solved it for me was changing "yaml.load(f)" to "yaml.safe_load(f)" in utils.py

**Comment by devhci** [comment]
@twarmuz I am, facing the same issue. How did you solve this ?

`

   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:5000 (Press CTRL+C to quit)
 * Restarting with stat
Navigate to http://localhost:5000/ for authorization.

 * Debugger is active!
 * Debugger PIN: 293-820-467
127.0.0.1 - - [06/May/2022 14:23:53] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?code=0ef91e5c6971b4178240959f963ee879 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\LBI\Desktop\accesslink\authorization.py", line 51, in callback
    token_response = accesslink.get_access_token(authorization_code)
  File "C:\Users\LBI\Desktop\accesslink\accesslink\accesslink.py", line 43, in get_access_token
    print(' What has been returned '+ self.oauth.get_access_token(authorization_code))
  File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 60, in get_access_token
    return self.post(endpoint=None,
  File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 128, in post
    return self.__request("post", endpoint=endpoint, **kwargs)
  File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 122, in __request
    return self.__parse_response(response)
  File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 109, in __parse_response
    raise HTTPError(message, response=response)
requests.exceptions.HTTPError: 400 Bad Request: {"error":"invalid_request"}
127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -


`

**Comment by ghost** [comment]
> @twarmuz I am, facing the same issue. How did you solve this ?
> 
> `
> 
> Use a production WSGI server instead.
> 
>     * Debug mode: on
> 
>     * Running on http://localhost:5000 (Press CTRL+C to quit)
> 
>     * Restarting with stat
>       Navigate to http://localhost:5000/ for authorization.
> 
>     * Debugger is active!
> 
>     * Debugger PIN: 293-820-467
>       127.0.0.1 - - [06/May/2022 14:23:53] "GET / HTTP/1.1" 302 -
>       127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?code=0ef91e5c6971b4178240959f963ee879 HTTP/1.1" 500 -
>       Traceback (most recent call last):
>       File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2095, in **call**
>       return self.wsgi_app(environ, start_response)
>       File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2080, in wsgi_app
>       response = self.handle_exception(e)
>       File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
>       response = self.full_dispatch_request()
>       File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
>       rv = self.handle_user_exception(e)
>       File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
>       rv = self.dispatch_request()
>       File "C:\Users\LBI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
>       return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>       File "C:\Users\LBI\Desktop\accesslink\authorization.py", line 51, in callback
>       token_response = accesslink.get_access_token(authorization_code)
>       File "C:\Users\LBI\Desktop\accesslink\accesslink\accesslink.py", line 43, in get_access_token
>       print(' What has been returned '+ self.oauth.get_access_token(authorization_code))
>       File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 60, in get_access_token
>       return self.post(endpoint=None,
>       File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 128, in post
>       return self.__request("post", endpoint=endpoint, **kwargs)
>       File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 122, in __request
>       return self.__parse_response(response)
>       File "C:\Users\LBI\Desktop\accesslink\accesslink\oauth2.py", line 109, in __parse_response
>       raise HTTPError(message, response=response)
>       requests.exceptions.HTTPError: 400 Bad Request: {"error":"invalid_request"}
>       127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?**debugger**=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
>       127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?**debugger**=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
>       127.0.0.1 - - [06/May/2022 14:23:54] "GET /oauth2_callback?**debugger**=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
> 
> 
> `

add to the data-dict in the oauth2.py the redirect_uri-key:

```
# ...

def get_access_token(self, authorization_code):

        headers = {
            "Content-Type" : "application/x-www-form-urlencoded",
            "Accept" : "application/json;charset=UTF-8"
        }

        data = {
            "grant_type" : "authorization_code",
            "redirect_uri" : self.redirect_url,
            "code" : authorization_code
        }
# ...


```
