### ISSUE TITLE
Authentication token request not working

### ISSUE THREAD

**Issue by RobertLeppich** [polarofficial/accesslink-example-python#25]
I'm trying to request an access token as described in the documentation: [Link](https://www.polar.com/accesslink-api/#token-endpoint).

The following request should be accurate according to the documentation. I tested to remove the redirect_uri, changed "code" with "authorization_code" similar to the example in the documentation, requested new client credentials and created a new API App for entirely new credentials. Nothing worked...

Request:
`curl -X POST -H "Accept: application/json;charset=UTF-8" -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Basic <Base64encoded(<client_id>:<client_secret>)>" -d 'grant_type=authorization_code&redirect_uri=<redirect_url>&code=<code>' 'https://polarremote.com/v2/oauth2/token'`

Resposne: (400)   
"error": "invalid_request"

**Comment by SenthamizhanV** [comment]
I'm facing the same issue here too. Tried everything - the requests keeps throwing `Response: 400`.

**Comment by RobertLeppich** [comment]
I was in contact with the Polar help desk regarding this issue. Here are some hints provided by them to solve the problem: (Spoiler: It was not helpful to solve my case.)

- Authorization code  expires in 10 minutes. This code must only be used once. If it's used more than once, the request will be denied and ALL issued tokens will be deleted. If an error occurs, this parameters is not present.
- You don't need to specify the redirect_uri parameter as the authorization callback domain you specified with the admin tool in client settings will be used anyway. If you use redirect_uri parameter then it must match the authorization callback domain because, unfortunately, dynamic redirect_uris are not supported.
- If the request still doesn't work, please make sure you don't have any extra spaces or characters for example in the authorization code.
- Also make sure the body content is either plain text or x-www-form-urlencoded

**Comment by SenthamizhanV** [comment]
Thank you very much for sharing this @GenBob! I tried these but it did not work for me too. I will keep looking for solutions.

**Comment by drazzilb91** [comment]
Did polar make a change to their authorization api? 

Previously, I used the parameter "redirect_uri" successfully, but now that does not work. However, "redirect_url" appears to work instead.

**Comment by hytka81** [comment]
It's still `redirect_uri` but (if provided) it needs to match the authorization redirect URL configured for the client. You can use https://admin.polaraccesslink.com/ to modify your existing client and change the redirect URL. By editing the client you can also add multiple redirect URLs in which case the parameter needs to match one of those.

I think that if you use something else, like `redirect_url` it will be discarded. Basically you would use `redirect_uri` if you have multiple redirect URLs specified for the client and want to use specific URL. Otherwise the one set as default will be used.
