### ISSUE TITLE
Polar Accesslink API v3 - webhook SLEEP

### ISSUE THREAD

**Issue by cdswan** [polarofficial/accesslink-example-python#29]
Hello, using the "webhook" API and enabling the SLEEP webhook I notice that when a device is synced the SLEEP web hook gets called two times (almost simultaneously) with the same data. Is this intended?

Separately, I note that the CONTINUOUS_HEART_RATE web hook is never called.

**Comment by hytka81** [comment]
Hey @cdswan. This requires more investigation but to me it sounds that it is not intended. SLEEP webhook is triggered based on notifications from another service(s) of the system but non the less this is something to be checked.
