### ISSUE TITLE
Trouble downloading data

### ISSUE THREAD

**Issue by LucaCerina** [polarofficial/accesslink-example-python#3]
Hello, I am having trouble downloading the data using the example application. 
I registered an application running in localhost with all authorizations checked.

I have authorized my user and the token is correctly created and I have some training sessions on Polar Flow.

I can get user informations, but on "check available data" it responds with no new data available.

How could I check what is going wrong?
Thank you

**Comment by vmhirvinen** [comment]
Currently only the activities and training sessions that has been synced after the user has authorized the application will be visible for application. Try to sync some more data to Polar Flow and see if that shows up in API?

**Comment by LucaCerina** [comment]
Ok, now it seems to work. However I am limited by a transaction on last available data, am I right? Or I can still retrieve all the training data?

Because with two subsequent calls, the first one sent me the data, but the second responded with no new exercises available.

**Comment by vmhirvinen** [comment]
Yes, only the data that has not been already fetched (as in committed in transaction) is returned. So you should save training session data in your end when you read it.
