### ISSUE TITLE
Authorization doesnt work

### ISSUE THREAD

**Issue by UtharaKeerthan** [polarofficial/accesslink-example-python#31]
Hi,

I cloned the repository and I edited the client id and client secret that is linked to my polar account
When I run the authorization.py script and click the generated local host link for authorization, I get the following error,
Is it normal? 
There is no way to proceed further to read the data from the device. 

![image](https://github.com/polarofficial/accesslink-example-python/assets/49371846/7a4c4e37-3031-452c-8bb4-ba5554513509)

Kindly provide your feedback.

**Comment by hytka81** [comment]
Hi @UtharaKeerthan! Please double check that you have configured authorization redirect URL correctly for your API client in https://admin.polaraccesslink.com. It needs to match the one in the README.md (`http://localhost:5000/oauth2_callback`). 

Also you don't need to specify `redirect_uri` when retrieving the code, just use URL that is mentioned in the README.md (`https://flow.polar.com/oauth2/authorization?response_type=code&client_id=<YOUR_CLIENT_ID>`). 

I have also just recently made some changes to the documentation and filenames etc. to hopefully clarify the process.

Hope this helps!
