### ISSUE TITLE
error in user registration

### ISSUE THREAD

**Issue by parag-shendye** [polarofficial/accesslink-example-python#33]
After getting the user access token, I am supposed to make a request to register the user with the user-id and the bearer token, I do it as following:
```
const headersPost = {
        'Content-Type':'application/json',  'Accept':'application/json',  'Authorization':`Bearer ${access_token}`
    };  
 const bodyPost = {
        "member-id": user_id
    };
 const resPost = await fetch("https://www.polaraccesslink.com/v3/users", { method: "POST", headers: headersPost, body: JSON.stringify(bodyPost)})
```
This however does not work. Then I tried the following, I basically added the "host" in header as www.polaraccesslink.com and it worked, but the documentation does not explain that. The error code is just 400 and there is no understandable error response. This worked:
```
const headersPost = {
        'Content-Type':'application/json',  'Accept':'application/json',  'Authorization':`Bearer ${access_token}`, 'Host':"www.polaraccesslink.com"
    };  
 const bodyPost = {
        "member-id": user_id
    };
 const resPost = await fetch("https://www.polaraccesslink.com/v3/users", { method: "POST", headers: headersPost, body: JSON.stringify(bodyPost)})
```

**Comment by hytka81** [comment]
Hi @parag-shendye! To my understanding `fetch()` should automatically add `Host` header which is derived from the request url. However, in your case it seems that it's not the case for some reason. I think it might be good idea to add something about the possible absence of the Host header to the documentation which results in HTTP 400 error.

**Comment by parag-shendye** [comment]
yes that should help, but I was also wondering why is the user registration needed when the token is generated by polar in the first place, I have also to worked with the Strava api and there the bearer token is enough for exchanging the data.

**Comment by hytka81** [comment]
You are right. This is legacy functionality that should be part of the code/token flow in the future.
