### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by ER7100** [polarofficial/accesslink-example-python#4]
Hi,
First, thanks for the example code. 
Meanwhile, I have been trying the authorization procedure by following the steps in the Readme (via filling config.yml and using authorization.py", etc.) and always end with a "400 Bad Request: {"error":"invalid_grant"}", when going to:

https://flow.polar.com/oauth2/authorization?response_type=code&client_id=XXX
where XXX is the value I added to config.yml.

Notice that when looking to my Profile/Partners, the application is listed as authorized. 

Using: Python (2.7.11); Flask (0.12.2); PyYAML (3.12); requests (2.18.1) // Safari 11.0.2 and Firefox (52.6.0) on macOS 10.12.6

Any idea?
Thanks

**Comment by vmhirvinen** [comment]
Can you please send your account details and client id to b2bhelpdesk@polar.com for futher investigation?

**Comment by tawfikbougerba** [comment]
I have problem with post request authentification while trying to run the code  I get this error { error: 'invalid_request' }



const  dat = {
              'grant_type': 'authorization_code',
              
              'code':code ,
               "redirect_uri" : redirect
               };
     
const URLSearchParams = Object.keys(dat).map((key) => {
  return encodeURIComponent(key) + '=' + encodeURIComponent(dat[key]);
}).join('&');


 fetch('https://polarremote.com/v2/oauth2/token',
 {

  method: 'POST',
  headers: {
    'Authorization':`Basic ${creds}`,
    
    'Content-Type': 'application/x-www-form-urlencoded',
     'Accept':'application/json; charset=utf-8'

  },
  data: URLSearchParams
 
}).then(function(res) {
    return res.json();
}).then(function(body) {
    console.log(body);
});

**Comment by vmhirvinen** [comment]
Redirect_uri should be used only if it was passed to authorization endpoint. 

Is it possible to provide correlation id (corrId from response header) for futher investigation?

**Comment by tawfik-1990** [comment]
I already have  with the code  thank you
 const  dat = {
              'grant_type': 'authorization_code',

              'code': `${code}`,
               'redirect_uri': `${redirect}`,
               };
     


      var date = querystring.stringify(dat);
var contentLength = dat.length;
request({
    headers: {
      'Content-Length': contentLength,
        'Content-Type': 'application/x-www-form-urlencoded',
     'Accept':'application/json; charset=utf-8',

     'Authorization':`Basic ${creds}`
    },

  uri: 'https://polarremote.com/v2/oauth2/token',
    body: date,
    method: 'POST'
  }, function (err, res, body) {
    if(err)
    {
      console.log(err);
    }
    console.log(body);
   
  });

**Comment by tawfik-1990** [comment]
I want to get refresh_token.
how can i get refresh token?
thank you

**Comment by lk1986** [comment]
I first got the exact same problem as ER71000 with https://flow.polar.com/oauth2/authorization?response_type=code&client_id=XXX and got the approval to my account. Then I realised the authentication.py asks to "Navigate to http://localhost:5000/ for authorization". After that I got approval and got the application working.

**Comment by WildWoila** [comment]
Thanks @lk1986, that did the trick! :)
