### ISSUE TITLE
enhancement request : sleep plus data

### ISSUE THREAD

**Issue by toxic0berliner** [polarofficial/accesslink-example-python#6]
Hello,

Looking at the documentation I cannot find infos to access my sleep data.
I'd be glad to be able to fetch these datas as well, time of start and end of sleep, steps of blue/yellow sleep/interuptions, sleep score, sleep rating by the user, ...

**Comment by valbosco** [comment]
Have you found a way to access the sleep data

**Comment by hytka81** [comment]
Hi! Sleep data is currently available in the API, more information here: https://www.polar.com/accesslink-api/#sleep
