### ISSUE TITLE
User/password issue

### ISSUE THREAD

**Issue by HughhguH** [polarofficial/accesslink-example-python#9]
I went through the code. Everything works fine and I get the available-data when I ask for.

However in the available-data I get several links in the field "polar-user". When I click on it I need to put user and password, Where can I find these last ones? I was expecting to retrieve continuous bpm activity data from this link. Is it the right way to get it?

Thanks

**Comment by vmhirvinen** [comment]
Please see https://www.polar.com/accesslink-api/#daily-activity for documentation how to programmatically get activity data using the links returned by data availability endpoint.
